# Generated by Django 4.0.1 on 2022-01-28 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvFiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfiles',
            name='csv',
            field=models.FileField(upload_to='FileReceiver/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
        migrations.AlterField(
            model_name='csvfiles',
            name='nome',
            field=models.CharField(default='testeParsing', max_length=50),
        ),
    ]
